// <auto-generated />
using System;
using BookingGuardian.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingGuardian.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    [Migration("20260315140354_AddCustomerEmailToExistingTable")]
    partial class AddCustomerEmailToExistingTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BookingGuardian.Models.Anomaly", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("detected_at");

                    b.Property<DateTime>("DetectionRunAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("detection_run_at");

                    b.Property<int?>("EndpointHealthId")
                        .HasColumnType("int")
                        .HasColumnName("endpoint_health_id");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("note");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("resolved_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("EndpointHealthId")
                        .HasDatabaseName("idx_anomaly_endpoint_health");

                    b.ToTable("anomalies", (string)null);
                });

            modelBuilder.Entity("BookingGuardian.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .HasColumnType("longtext")
                        .HasColumnName("detail");

                    b.Property<int>("EntityId")
                        .HasColumnType("int")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("note");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("performed_by");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_performed_at");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("idx_entity");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("BookingGuardian.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("booking_status");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("customer_name");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("operator_name");

                    b.Property<byte>("PassengerCount")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("passenger_count");

                    b.Property<DateTime?>("PaymentAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("payment_at");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("payment_status");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("ReferenceNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("reference_no");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("route");

                    b.Property<DateTime>("TravelDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("travel_date");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceNo")
                        .IsUnique();

                    b.HasIndex("PaymentStatus", "BookingStatus", "PaymentAt")
                        .HasDatabaseName("idx_anomaly_detection");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("BookingGuardian.Models.EndpointHealth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("checked_at");

                    b.Property<int?>("HttpCode")
                        .HasColumnType("int")
                        .HasColumnName("http_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int?>("ResponseMs")
                        .HasColumnType("int")
                        .HasColumnName("response_ms");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("Name", "CheckedAt")
                        .HasDatabaseName("idx_name_time");

                    b.ToTable("endpoint_health", (string)null);
                });

            modelBuilder.Entity("BookingGuardian.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BookingGuardian.Models.Anomaly", b =>
                {
                    b.HasOne("BookingGuardian.Models.Booking", "Booking")
                        .WithOne("Anomaly")
                        .HasForeignKey("BookingGuardian.Models.Anomaly", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingGuardian.Models.EndpointHealth", "EndpointHealth")
                        .WithMany("Anomalies")
                        .HasForeignKey("EndpointHealthId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Booking");

                    b.Navigation("EndpointHealth");
                });

            modelBuilder.Entity("BookingGuardian.Models.Booking", b =>
                {
                    b.Navigation("Anomaly");
                });

            modelBuilder.Entity("BookingGuardian.Models.EndpointHealth", b =>
                {
                    b.Navigation("Anomalies");
                });
#pragma warning restore 612, 618
        }
    }
}
