using BookingGuardian.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace BookingGuardian.Services
{
    public interface IMonthlyPdfReportService
    {
        Task<byte[]> GenerateMonthlyReportPdfAsync(int year, int month);
    }

    public class MonthlyPdfReportService : IMonthlyPdfReportService
    {
        private readonly IReportService _reportService;

        public MonthlyPdfReportService(IReportService reportService)
        {
            _reportService = reportService;
        }

        public async Task<byte[]> GenerateMonthlyReportPdfAsync(int year, int month)
        {
            var data = await _reportService.BuildMonthlyReportDataAsync(year, month);

            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(30);
                    page.DefaultTextStyle(x => x.FontSize(11));

                    page.Header().Column(col =>
                    {
                        col.Item().Text("TicketGuard — Monthly Report").FontSize(20).Bold();
                        col.Item().Text(new DateTime(year, month, 1).ToString("MMMM yyyy"));
                        col.Item().Text($"Generated at: {data.GeneratedAtUtc:yyyy-MM-dd HH:mm:ss} UTC").FontColor(Colors.Grey.Darken2);
                    });

                    page.Content().Column(col =>
                    {
                        col.Spacing(10);

                        if (!data.HasData)
                        {
                            col.Item().PaddingTop(30).Text("No data available").FontSize(16).Bold();
                            return;
                        }

                        col.Item().Text("Section 1 — Summary").Bold();
                        col.Item().Table(t =>
                        {
                            t.ColumnsDefinition(c =>
                            {
                                c.RelativeColumn(3);
                                c.RelativeColumn(2);
                            });

                            AddMetricRow(t, "Total Booking Issues Detected", data.TotalAnomaliesDetected.ToString());
                            AddMetricRow(t, "Resolved", data.Resolved.ToString());
                            AddMetricRow(t, "Ignored", data.Ignored.ToString());
                            AddMetricRow(t, "Unresolved (still OPEN)", data.Unresolved.ToString());
                            AddMetricRow(t, "Revenue Recovered", $"฿{data.RevenueRecovered:N2}");
                            AddMetricRow(t, "Mean Time to Resolve", $"{data.MeanTimeToResolve:N1} minutes");
                        });

                        col.Item().Text("Section 2 — Endpoint Uptime").Bold();
                        col.Item().Table(t =>
                        {
                            t.ColumnsDefinition(c =>
                            {
                                c.RelativeColumn(3);
                                c.RelativeColumn(2);
                                c.RelativeColumn(2);
                            });

                            AddHeaderRow(t, "Endpoint", "Uptime %", "Total DOWN events");
                            foreach (var row in data.EndpointUptime)
                            {
                                AddDataRow(t, row.Endpoint, row.UptimePercent.ToString("N2"), row.DownEvents.ToString());
                            }
                        });

                        col.Item().Text("Section 3 — Top 3 Booking Issue Causes").Bold();
                        if (!data.TopCauses.Any())
                        {
                            col.Item().Text("- No booking issue causes found");
                        }
                        else
                        {
                            foreach (var cause in data.TopCauses.Select((value, index) => new { value, index }))
                            {
                                col.Item().Text($"{cause.index + 1}. {cause.value.Cause} ({cause.value.Count})");
                            }
                        }

                        col.Item().Text("Section 4 — Recommendation").Bold();
                        foreach (var recommendation in data.Recommendations)
                        {
                            col.Item().Text($"- {recommendation}");
                        }
                    });

                    page.Footer()
                        .AlignCenter()
                        .Text("Generated by TicketGuard | Internal Use Only")
                        .FontColor(Colors.Grey.Darken1);
                });
            });

            return document.GeneratePdf();
        }

        private static void AddMetricRow(TableDescriptor table, string metric, string value)
        {
            table.Cell().Element(CellStyle).Text(metric);
            table.Cell().Element(CellStyle).Text(value);
        }

        private static void AddHeaderRow(TableDescriptor table, string c1, string c2, string c3)
        {
            table.Cell().Element(HeaderCellStyle).Text(c1).Bold();
            table.Cell().Element(HeaderCellStyle).Text(c2).Bold();
            table.Cell().Element(HeaderCellStyle).Text(c3).Bold();
        }

        private static void AddDataRow(TableDescriptor table, string c1, string c2, string c3)
        {
            table.Cell().Element(CellStyle).Text(c1);
            table.Cell().Element(CellStyle).Text(c2);
            table.Cell().Element(CellStyle).Text(c3);
        }

        private static IContainer CellStyle(IContainer container)
        {
            return container.Border(1).BorderColor(Colors.Grey.Lighten2).Padding(6);
        }

        private static IContainer HeaderCellStyle(IContainer container)
        {
            return container.Background(Colors.Grey.Lighten3).Border(1).BorderColor(Colors.Grey.Lighten2).Padding(6);
        }
    }
}
